name: Waka Readme

on:
  push:
    branches: [ main ]        # temporary: triggers immediately on every push
  workflow_dispatch: {}        # enables “Run workflow” manually
  schedule:
    - cron: '0 0 * * *'        # runs daily at midnight UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository so athul/waka-readme can see README.md
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Generate and inject WakaTime metrics into README.md
      - name: Generate WakaTime Weekly Metrics
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      # 3) Commit any README.md changes back to main
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update WakaTime stats
          file_pattern: README.md
          author_name: github-actions
          author_email: actions@github.com
